name: Publish Docs

on:
  workflow_run:
    workflows: ["Build & Test"]
    branches: [ "master" ]
    types: [ completed ]


permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true


jobs:

  publish_docs:
    runs-on: ubuntu-latest
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    steps:
      - uses: actions/checkout@v3

      - name: Compile Docs
        run: cargo doc --no-deps

      - name: Copy redirect index.html
        run: cp .github/res/doc_redirect.html target/doc/index.html

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'target/doc/'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1


